from typing import Protocol


class MemoryStore(Protocol):
    async def append(self, session_id: str, role: str, content: str) -> None: ...
    async def recent(self, session_id: str, limit: int = 10) -> list[dict]: ...
    async def clear(self, session_id: str) -> None: ...
